version: '3.1'

services:
  heplify-server:
    image: artifactory.devops.maaii.com/lc-docker-local/m800-heplify-server:latest
    container_name: m800-heplify-server
    volumes:
      - ./config-files/heplify-server.toml:/root/heplify-server.toml
    ports:
      - "9096:9096/tcp"
      - "9060:9060"
      - "9060:9060/udp"
    command:
      - './heplify-server'
    restart: unless-stopped
