{
 "title": "M800 SIP Overview",
 "time": { "from": "2019-10-29T22:00:00.000Z", "to": "2019-10-29T23:59:59.000Z" },
 "panels": [
  {
   "title": "Call Fail Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(heplify_method_response{method=\"INVITE\", response=~\"408|480|487|500\"}[10m])) / \nsum(rate(heplify_method_response{method=\"INVITE\", response=\"INVITE\"}[10m])) * 100)",
     "legendFormat": "Fail rate"
    }
   ]
  },
  {
   "title": "Concurrent call",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(increase(heplify_method_response{method=\"INVITE\", response=\"200\"}[5m]))",
     "legendFormat": "Concurrent call"
    }
   ]
  },
  {
   "title": "Calls per second & Call attempts per second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(heplify_method_response{method=\"INVITE\", response=\"200\"}[10s]))",
     "legendFormat": "CPS"
    }
   ]
  }
 ]
}